---
apiVersion: v1
kind: Service
metadata:
  name: messagingservice
spec:
  selector:
    app: django-app
    version: green
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP