#!/bin/bash

echo "About to start Kubernetes"
minikube start
sleep 1s
echo "About to verify that cluster is running"
kubectl cluster-info
sleep 1s
echo "About to retrieve available pods"
kubectl get pods
echo "Script automation ended"
