# Generated by Django 5.2.4 on 2025-07-30 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_message_edited'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modifier', models.CharField(blank=True, max_length=255)),
                ('recipient', models.CharField(blank=True, max_length=255)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('old_content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='message_history', to='messaging.message')),
            ],
        ),
    ]
