# Generated by Django 5.2.4 on 2025-07-30 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_alter_notification_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagehistory',
            name='old_content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_history', to='messaging.message'),
        ),
    ]
