# Generated by Django 5.2.4 on 2025-07-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_alter_messagehistory_old_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagehistory',
            name='old_content',
            field=models.TextField(blank=True),
        ),
    ]
