# Generated by Django 5.2.4 on 2025-07-30 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0006_alter_messagehistory_old_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagehistory',
            old_name='date_modified',
            new_name='edited_at',
        ),
        migrations.RenameField(
            model_name='messagehistory',
            old_name='modifier',
            new_name='edited_by',
        ),
    ]
