# Generated by Django 5.2.4 on 2025-07-30 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0007_rename_date_modified_messagehistory_edited_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='receiver',
            new_name='parent_message',
        ),
    ]
