name: Build and Push Docker Image

on:
  push:
    branches:
      - main # Trigger on pushes to the 'main' branch
  pull_request:
    branches:
      - main # Trigger on pull requests targeting the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest # Specify the runner environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Action to checkout the repository code

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # Docker Hub username stored as a secret
          password: ${{ secrets.DOCKER_PASSWORD }} # Docker Hub password/PAT stored as a secret

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: . # Build context (current directory)
          file: ./Dockerfile # Path to your Dockerfile
          push: true # Push the image to Docker Hub
          tags: your-dockerhub-username/messaging-app:latest # Tag for the Docker image