# Generated by Django 5.2.4 on 2025-07-25 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_rename_participants_id_conversation_participants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='message',
            field=models.ForeignKey(default='a37c4b97fe9349b694a109b77fb693da', on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='chats.message'),
            preserve_default=False,
        ),
    ]
