pipeline {
    agent {
        docker {
            image 'python:3.10'   // official Python image with pip preinstalled
        }
    }

    stages {
        stage('Build') {
            steps {
                echo 'Building...'
                git branch: 'main',
                    url: 'https://github.com/Limah-T/alx-backend-python.git',
                    credentialsId: 'github-creds'

                echo 'Installing dependencies...'
                sh 'pip install -r messaging_app/requirements.txt'
            }
        }

        stage('Test') {
            steps {
                sh 'pytest messaging_app/ --junitxml=report.xml'
            }
            post {
                always {
                    junit 'report.xml'
                }
            }
        }
    }
}
