pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building...'
                git branch: 'main',
                    url: 'https://github.com/Limah-T/alx-backend-python.git',
                    credentialsId: 'github-creds'

                withPythonEnv('python3') {
                    echo 'Installing dependencies...'
                    sh 'pip install -r messaging_app/requirements.txt'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    def appImage = docker.build("limtech001/messaging_app:${env.BUILD_ID}", "-f messaging_app/Dockerfile .")

                    docker.withRegistry('https://index.docker.io/v1/', 'dockerhub-creds') {
                        echo 'Pushing Docker image to Docker Hub...'
                        appImage.push()         // BUILD_ID
                        appImage.push("latest")
                        appImage.push("v1.0")
                    }
                }
            }
        }

        stage('Test') {
            steps {
                sh 'python3 -m venv venv'
                sh '. venv/bin/activate && pip install -r requirements.txt'
                sh '. venv/bin/activate && pytest --junitxml=report.xml'
            }
        }


        stage('Deploy') {
            steps {
                echo 'Deploying...'
                sh 'kubectl apply -f deployment.yaml'
                sh 'kubectl get pods'
            }
        }
    }
}
